computer_app_web/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from products.views import index_views, customer_views
from products.views import views_products
from products.views import views_laptop
from products.views import views_pc
from products.views import monitor_views
from products.views import views_peripheral
app_name = "cart"
from cart import views_car

urlpatterns = [
    path('admin/', admin.site.urls),
    path('New_computer/', index_views.views, name='index'),

    # views data in the app
    path('products/', views_products.database_views, name='view_products'),
    path('products/laptop/', views_laptop.database_laptop, name='view_laptops'),
    path('products/pc/', views_pc.database_pc, name='view_pc'),
    path('products/monitors/', monitor_views.database_monitor, name='view_monitors'),
    path('products/type-peripheral/', views_peripheral.database_type, name='view_type-peripheral'),
    path('products/type/<int:id>', views_peripheral.data_typeperipheral, name='type_peripheral'),

    # detail data in the products of the app
    path('products/detail/peripheral/<int:id>', views_peripheral.detail_peripheral, name='detail_peripheral'),
    path('products/detail/pc/<int:id>', views_pc.detail_pc, name='detail_pc'),
    path('products/detail/monitor/<int:id>', monitor_views.detail_monitor, name='detail_monitor'),
    path('products/detail/laptop/<int:id>', views_laptop.detail_laptop, name='detail_laptop'),

    # create data by website
    path('products/create/', views_products.create_data, name="product_create"),
    path('products/create/laptop/', views_laptop.create_laptop, name="laptop_create"),
    path('products/create/laptops/', views_laptop.create_laptops, name="laptops_create"),
    path('products/create/monitor/', monitor_views.create_monitor, name="monitor_create"),
    path('products/create/monitors/', monitor_views.create_monitors, name="monitors_create"),
    path('products/create/pc/', views_pc.create_pc, name="pc_create"),
    path('products/create/pcs/', views_pc.create_pcs, name="pcs_create"),
    path('products/create/peripheral/', views_peripheral.create_peripheral, name="peripheral_create"),

    # Update data in one element choose by id
    url(r'^products/update/laptop/(?P<id>\d+)/$', views_laptop.update_laptop, name='update_laptop'),
    url(r'^products/update/monitor/(?P<id>\d+)/$', monitor_views.update_monitor, name='update_monitor'),
    url(r'^products/update/pc/(?P<id>\d+)/$', views_pc.update_pc, name='update_pc'),
    url(r'^products/update/peripheral/(?P<id>\d+)/$', views_peripheral.update_peripheral, name='update_peripheral'),

    # delete data of the database
    url(r'^products/delete(?P<id>\d+)/$', views_products.delete_data, name='delete_products'),
    url(r'^products/delete/laptop/(?P<id>\d+)/$', views_laptop.delete_laptop, name='delete_laptop'),
    url(r'^products/delete/monitor/(?P<id>\d+)/$', monitor_views.delete_monitor, name='delete_monitor'),
    url(r'^products/delete/pc/(?P<id>\d+)/$', views_pc.delete_pc, name='delete_pc'),
    url(r'^products/delete/peripheral/(?P<id>\d+)/$', views_peripheral.delete_peripheral, name='delete_peripheral'),

    # filter
    path('product/filter/', views_products.filter_one_product, name='filter_product'),

    # customer and user
    path('customer/create/', customer_views.create_user, name='user_create'),
    path('customer/login/', customer_views.login_view, name='login'),
    path('customer/logout/', customer_views.logout_v, name='logout'),

    # Super user methods
    path('superuser/create/', customer_views.create_superuser, name='superuser_create'),
    path('superuser/views/', customer_views.views_user, name='views_user'),
    path('superuser/delete/<int:id>', customer_views.delete_user, name='delete_user'),

    # car
    path('car/add_product/<int:product_id>/', views_car.add_product, name='add_product'),
    path('car/delete_product/<int:product_id>/', views_car.delete_product, name='delete_product'),
    path('car/subtract_product/<int:product_id>/', views_car.subtract_product, name='subtract_product'),
    path('car/clean_product/', views_car.clean_car, name='clean_product'),
    path('car/', index_views.cart, name='view_car'),

    # Send mail
    path('sendmail/', views_car.email, name='send_mail')


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user

    class Meta:
        db_table = 'customer'


class Bill(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    data_buy = models.DateTimeField()

    def __str__(self):
        return str(self.id)

    def bill_id(self):
        return 'Bill' + str(self.id)

    def get_cost_total(self):
        return sum(item.get_cost() for item in self.items.all())

    class Meta:
        db_table = 'bill'


class Products(models.Model):
    name = models.CharField(max_length=50)
    description_general = models.CharField(max_length=400)
    image = models.ImageField(upload_to='resouce')
    price = models.IntegerField('Price')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'products'


class Detail(models.Model):
    amount = models.IntegerField(default=1)
    product_id = models.ForeignKey(Products, related_name='items_order', on_delete=models.CASCADE)
    bill_id = models.ForeignKey(Bill, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField('Price')

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.amount

    class Meta:
        db_table = 'detail'


class Laptop(models.Model):
    products = models.ForeignKey(Products, on_delete=models.CASCADE)

    def __str__(self):
        return self.products.name

    class Meta:
        db_table = 'laptop'


class Laptops_character(models.Model):
    laptops = models.ForeignKey(Laptop, on_delete=models.CASCADE)
    graphic_card = models.CharField(max_length=100)
    keyboard = models.CharField(max_length=100)
    display = models.CharField(max_length=100)
    processor = models.CharField(max_length=50)
    memory = models.CharField(max_length=50)
    storage = models.CharField(max_length=50)
    warranty = models.CharField(max_length=100)

    def __str__(self):
        return self.laptops.products.name

    class Meta:
        db_table = 'laptops_character'


class Type_peripheral(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'type_peripheral'


class Peripheral(models.Model):
    products = models.ForeignKey(Products, on_delete=models.CASCADE)
    type_peripherals = models.ForeignKey(Type_peripheral, on_delete=models.CASCADE)
    description = models.CharField(max_length=400)
    link_website = models.CharField(max_length=300)

    def __str__(self):
        return self.products.name

    class Meta:
        db_table = 'peripheral'


class Monitor(models.Model):
    products = models.ForeignKey(Products, on_delete=models.CASCADE)

    def __str__(self):
        return self.products.name

    class Meta:
        db_table = 'monitor'


class Monitor_character(models.Model):
    monitors = models.ForeignKey(Monitor, on_delete=models.CASCADE)
    size = models.CharField(max_length=100)
    hz = models.CharField(max_length=100)
    quality = models.CharField(max_length=100)

    def __str__(self):
        return self.monitors.products.name

    class Meta:
        db_table = 'monitor_character'


class Pc(models.Model):
    products = models.ForeignKey(Products, on_delete=models.CASCADE)

    def __str__(self):
        return self.products.name

    class Meta:
        db_table = 'pc'


class Pc_character(models.Model):
    pcs = models.ForeignKey(Pc, on_delete=models.CASCADE)
    peripherals = models.ForeignKey(Peripheral, on_delete=models.CASCADE)
    graphic_card = models.CharField(max_length=100)
    board = models.CharField(max_length=100)
    monitors = models.ForeignKey(Monitor, on_delete=models.CASCADE)
    processor = models.CharField(max_length=50)
    memory = models.CharField(max_length=50)
    storage = models.CharField(max_length=50)
    refrigeration = models.CharField(max_length=100)

    def __str__(self):
        return self.pcs.products.name

    class Meta:
        db_table = 'pc_character'

products/forms/laptop_form.py
from django import forms
from products.models import Laptops_character, Laptop


class laptop_form(forms.ModelForm):
    class Meta:
        model = Laptops_character
        fields = [
            'laptops',
            'graphic_card',
            'keyboard',
            'display',
            'processor',
            'memory',
            'storage',
            'warranty',
        ]


class laptops_form(forms.ModelForm):
    class Meta:
        model = Laptop
        fields = [
            'products'
        ]

products/views/customer_views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from products.forms import customer_form, superuser_form
from products.models import Customer, User


def create_user(request):
    data = {
        'form': customer_form
    }
    if request.method == 'POST':
        form_user = customer_form(data=request.POST)
        if form_user.is_valid():
            form_user.save()
            messages.info(request, 'User create in the system.')
            user = authenticate(username=form_user.cleaned_data["username"],
                                password=form_user.cleaned_data['password1'])
            login(request, user)
            return redirect('index')
        data
    return render(request, 'user_customer/user_create.html', data)


@permission_required('products.add_products')
def create_superuser(request):
    data = {
        'form': superuser_form
    }
    if request.method == 'POST':
        form_user = superuser_form(data=request.POST)
        if form_user.is_valid():
            form_user.save()
            user = authenticate(username=form_user.cleaned_data["username"],
                                password=form_user.cleaned_data['password1'])
            login(request, user)
            return redirect('index')
        data
    return render(request, 'user_customer/superuser_create.html', data)


def login_view(request):
    if request.method == 'POST':
        _username = request.POST['username']
        _password = request.POST['password']
        user = authenticate(request, username=_username, password=_password)
        print(user)
        if user:
            login(request, user)
            return redirect('index')
        else:
            return render(request, 'user_customer/login.html', {'error': 'User do not register in database'})

    return render(request, 'user_customer/login.html')


@login_required
def logout_v(request):
    logout(request)
    return redirect('index')


def views_user(request):
    list_user = User.objects.all()
    return render(request, 'user_customer/user_view.html', {'list': list_user})


@permission_required('products.delete_products')
def delete_user(request, id):
    user_get = User.objects.get(id=id)
    if request.method == 'POST':
        user_get.delete()
        messages.info(request, 'Delete user in the system.')
        return redirect('views_user')
    return render(request, {'user': user_get})

products/views/index_views.py
from django.shortcuts import render


def views(request):
    return render(request, 'user_customer/index.html')


def cart(request):
    return render(request, 'car/car_view.html')

products/views/monitor_views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect
from products.models import Monitor, Products, Monitor_character
from products.forms import monitor_form, monitors_form


def database_monitor(request):
    list_monitors = Monitor.objects.all()
    return render(request, 'monitor/monitors_view.html', {'lists': list_monitors})


def detail_monitor(request, id):
    item = Products.objects.get(id=id)
    item_monitor = Monitor_character.objects.all().filter(monitors__products_id=id)
    return render(request, 'monitor/monitor_detail.html', {'item': item, 'item_monitor': item_monitor})


@permission_required('products.add_monitor_character')
def create_monitor(request):
    if request.method == 'POST':
        form = monitor_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img_obj = form.instance
            data_save = {
                'form': form,
                'img_obj': img_obj
            }
            messages.info(request, 'create monitor in the database.')
            return render(request, 'monitor/monitor_create.html', data_save)
    else:
        form = monitor_form
    return render(request, 'monitor/monitor_create.html', {'form': form})


@permission_required('products.add_monitor')
def create_monitors(request):
    if request.method == 'POST':
        form_l = monitors_form(request.POST, request.FILES)
        if form_l.is_valid():
            form_l.save()
            img_obj = form_l.instance
            messages.info(request, 'Save data, press the next button.')
            return render(request, 'monitor/monitors_create.html', {'form_l': form_l, 'img_obj': img_obj})
    else:
        form_l = monitors_form()
    return render(request, 'monitor/monitors_create.html', {'form_l': form_l})


@permission_required('products.change_monitor_character')
def update_monitor(request, id):
    monitor = Monitor_character.objects.get(monitors__products_id=id)
    update_form = monitor_form(request.POST or None, instance=monitor)
    if update_form.is_valid():
        update_form.save()
        messages.info(request, 'Update to the monitor in the database.')
        return redirect('/products/update/monitor/'+id)

    name_product = Monitor.objects.get(products_id=id)
    context = {
        'update_form': update_form,
        'name': name_product
    }
    return render(request, 'monitor/monitor_update.html', context)


@permission_required('products.delete_monitor')
def delete_monitor(request, id):
    monitor_get = Monitor.objects.get(id=id)
    if request.method == 'POST':
        monitor_get.delete()
        messages.info(request, 'Data delete on the database.')
        return redirect('view_monitors')
    return render(request, {'monitor': monitor_get})

products/views/views_laptop.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect
from products.forms import laptop_form, laptops_form
from products.models import Laptop, Products, Laptops_character
from django.contrib import messages


def database_laptop(request):
    products_list = Laptop.objects.all()
    return render(request, 'laptop/view_laptop.html', {'lists': products_list})


def detail_laptop(request, id):
    item = Products.objects.get(id=id)
    item_l = Laptops_character.objects.all().filter(laptops__products_id=id)
    return render(request, 'laptop/laptop_detail.html', {'item': item, 'item_l': item_l})


@permission_required('products.add_laptops_character')
def create_laptop(request):
    if request.method == 'POST':
        form = laptop_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img_obj = form.instance
            data_save = {
                'form': form,
                'img_obj': img_obj,
            }
            messages.info(request, 'Save data, go to laptop.')
            return render(request, 'laptop/laptop_create.html', data_save)
    else:
        form = laptop_form()
    return render(request, 'laptop/laptop_create.html', {'form': form})


@permission_required('products.add_laptop')
def create_laptops(request):
    if request.method == 'POST':
        form_l = laptops_form(request.POST, request.FILES)
        if form_l.is_valid():
            form_l.save()
            img_obj = form_l.instance
            messages.info(request, 'Save data, press the next button.')
            data_save = {
                'img_obj': img_obj,
                'form_l': form_l
            }
            return render(request, 'laptop/laptops_create.html', data_save)
    else:
        form_l = laptops_form()
    return render(request, 'laptop/laptops_create.html', {'form_l': form_l})


@permission_required('products.add_laptop_character')
def update_laptop(request, id):
    laptop = Laptops_character.objects.get(laptops__products_id=id)
    update_form = laptop_form(request.POST or None, instance=laptop)
    if update_form.is_valid():
        update_form.save()
        messages.info(request, 'Update laptop in the database.')
        return redirect('/products/update/laptop/' + id)
    name_product = Laptop.objects.get(products_id=id)
    context = {
        'update_form': update_form,
        'name': name_product
    }
    return render(request, 'laptop/laptop_update.html', context)


@permission_required('products.delete_laptop')
def delete_laptop(request, id):
    laptop_get = Laptop.objects.get(id=id)
    if request.method == 'POST':
        laptop_get.delete()
        messages.info(request, 'Data delete on the database.')
        return redirect('view_laptops')
    return render(request, {'laptop': laptop_get})

products/templates/monitor/monitor_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Create monitor</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Stint+Ultra+Condensed&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pattaya&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
          integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">


</head>
<body>
<nav class="nav">

    <ul class="nav__ul">
        <div class="nav__ul--margin">
                {% if perms.products.add_products %}
            <li class="nav__li right"><i class=""></i><a href="{% url 'views_user' %}">User</a></li>
        {% endif %}
            <li class="nav__li right"><i class=""></i><a href="{% url 'index' %}">Index</a></li>
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_products' %}">Products</a></li>
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_laptops' %}">Laptops</a></li>
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_pc' %}">Pc</a></li>
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_monitors' %}">Monitors</a></li>
            <li class="nav__li right"><a href="{% url 'view_type-peripheral' %}">Peripheral</a></li>
            <li class="nav__li left"><a href=""><i class="fas fa-cart-arrow-down"></i></a></li>
            <li class="nav__li left"><a href="{% url 'filter_product' %}"><i class="fas fa-search"></i></a></li>
            <li class="nav__li left"><a href="{% url 'user_create' %}"><i class="fas fa-user-plus"></i></a></li>

            {% if perms.products.add_monitor %}
                <li class="nav__li left"><a href="{% url 'monitors_create' %}"><i class="fas fa-save"></i></a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav__li left"><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
            {% else %}
                <li class="nav__li left"><a href="{% url 'login' %}"><i class="fas fa-users"></i></a></li>
            {% endif %}
        </div>
    </ul>

    <ul class="nav__responsive-ul">
        <div class="nav__responsive-button-container">
            <div class="nav__responsive-button"><i class="fas fa-bars"></i></div>
        </div>
        <div class="nav__li-container">
                {% if perms.products.add_products %}
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'views_user' %}">User</a></li>
        {% endif %}
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'index' %}">Index</a></li>
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_products' %}">Products</a></li>
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_laptops' %}">Laptops</a></li>
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_pc' %}">Pc</a></li>
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_monitors' %}">Monitors</a></li>
            <li class="nav__responsive-li"><a href="{% url 'view_type-peripheral' %}">Peripheral</a></li>
            <li class="nav__responsive-li"><a href=""><i class="fas fa-cart-arrow-down"></i></a></li>
            <li class="nav__responsive-li"><a href="{% url 'filter_product' %}"><i class="fas fa-search"></i></a></li>
            <li class="nav__li"><a href="{% url 'user_create' %}"><i class="fas fa-user-plus"></i></a></li>

            {% if perms.products.add_monitor %}
                <li class="nav__li"><a href="{% url 'monitors_create' %}"><i class="fas fa-save"></i></a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav__li"><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
            {% else %}
                <li class="nav__li"><a href="{% url 'login' %}"><i class="fas fa-users"></i></a></li>
            {% endif %}
        </div>
    </ul>
</nav>

<div class="section_update">
    <form method="post" enctype="multipart/form-data">
        {% if messages %}
            <ul class="messages_update">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    <li><a href="{% url 'view_monitors' %}">Go to see monitors</a></li>
                {% endfor %}
            </ul>
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create monitor</button>
    </form>
</div>
<footer class="footer">
    <ul class="ul">
        <li><a href=""><img src="{% static 'image/logo_facebook.png' %}"></a></li>
        <li><a href=""><img src="{% static 'image/logo_instagram.jpg' %}"></a></li>
        <li><a href="tel:3333333"><img src="{% static 'image/logo_whatsapp.jpg' %}"></a></li>
        <li><a href=""><img src="{% static 'image/logo_youtube.jpg' %}"></a></li>

    </ul>
    <div class="name">
        <p>Santiago Andres Arias Mancilla</p>

    </div>
</footer>

</body>
</html>

products/templates/monitor/monitor_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{{ item.name }}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Stint+Ultra+Condensed&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pattaya&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
          integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">


</head>
<body>
<nav class="nav">

    <ul class="nav__ul">
        <div class="nav__ul--margin">
            {% if perms.products.add_products %}
                <li class="nav__li right"><i class=""></i><a href="{% url 'views_user' %}">User</a></li>
            {% endif %}
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_products' %}">Products</a></li>
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_laptops' %}">Laptops</a></li>
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_pc' %}">Pc</a></li>
            <li class="nav__li right"><i class=""></i><a href="{% url 'view_monitors' %}">Monitors</a></li>
            <li class="nav__li right"><a href="{% url 'view_type-peripheral' %}">Peripheral</a></li>
            <li class="nav__li right"><a href="">Total: {{ import_total_cart }}</a></li>
            <li class="nav__li left"><a href="{% url 'view_car' %}"><i class="fas fa-cart-arrow-down"></i></a></li>
            <li class="nav__li left"><a href="{% url 'filter_product' %}"><i class="fas fa-search"></i></a></li>
            <li class="nav__li left"><a href="{% url 'user_create' %}"><i class="fas fa-user-plus"></i></a></li>

            {% if perms.products.add_monitor %}
                <li class="nav__li left"><a href="{% url 'monitors_create' %}"><i class="fas fa-save"></i></a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav__li left"><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
            {% else %}
                <li class="nav__li left"><a href="{% url 'login' %}"><i class="fas fa-users"></i></a></li>
            {% endif %}
        </div>
    </ul>

    <ul class="nav__responsive-ul">
        <div class="nav__responsive-button-container">
            <div class="nav__responsive-button"><i class="fas fa-bars"></i></div>
        </div>
        <div class="nav__li-container">
            {% if perms.products.add_products %}
                <li class="nav__responsive-li"><i class=""></i><a href="{% url 'views_user' %}">User</a></li>
            {% endif %}
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_products' %}">Products</a></li>
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_laptops' %}">Laptops</a></li>
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_pc' %}">Pc</a></li>
            <li class="nav__responsive-li"><i class=""></i><a href="{% url 'view_monitors' %}">Monitors</a></li>
            <li class="nav__responsive-li"><a href="{% url 'view_type-peripheral' %}">Peripheral</a></li>
            <li class="nav__responsive-li"><a href=""><i class="fas fa-cart-arrow-down"></i></a></li>
            <li class="nav__responsive-li"><a href="{% url 'filter_product' %}"><i class="fas fa-search"></i></a></li>
            <li class="nav__responsive-li"><a href="{% url 'user_create' %}"><i class="fas fa-user-plus"></i></a></li>

            {% if perms.products.add_monitor %}
                <li class="nav__responsiveli"><a href="{% url 'monitors_create' %}"><i class="fas fa-save"></i></a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav__responsive-li"><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
            {% else %}
                <li class="nav__responsive-li"><a href="{% url 'login' %}"><i class="fas fa-users"></i></a></li>
            {% endif %}
        </div>
    </ul>
</nav>

<div class="section">
    {% if messages %}
        <ul class="messages_view">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="card_detail_pc">
        <img src="{{ item.image.url }}" width="400" height="400">

        <h2 class="img_monitor">{{ item.name }}</h2>
        <h3>$ {{ item.price }}</h3>
    {% for item_m in item_monitor %}
        {% if perms.products.change_monitor %}
            <a href="{% url 'update_monitor' item_m.monitors.products.id %}" class="update">Update monitor</a>
        {% endif %}
            <div id="button">
                <form action="{% url 'add_product' item.id %}" class="form_buy  monitor_ri">
                    <input type="submit" value="Buy">
                </form>
            </div>
            <ul>
                <li><b>Size: </b>{{ item_m.size }}</li>
                <li><b>Hz: </b>{{ item_m.hz }}</li>
                <li><b>Quality: </b>{{ item_m.quality }}</li>

            </ul>

        {% endfor %}

    </div>
</div>
<footer class="footer">
    <ul class="ul">
        <li><a href=""><img src="{% static 'image/logo_facebook.png' %}"></a></li>
        <li><a href=""><img src="{% static 'image/logo_instagram.jpg' %}"></a></li>
        <li><a href="tel:3333333"><img src="{% static 'image/logo_whatsapp.jpg' %}"></a></li>
        <li><a href=""><img src="{% static 'image/logo_youtube.jpg' %}"></a></li>

    </ul>
    <div class="name">
        <p>Santiago Andres Arias Mancilla</p>

    </div>
</footer>

</body>
</html>